import { Component, EventEmitter, Output } from '@angular/core';
import { MatDialogRef } from '@angular/material';

@Component({
  selector: 'app-autocomp',
  templateUrl: './autocomp.component.html'
})
export class AutocompComponent {
  title = 'primeng-material';
  public dateValue = '';
  options: string[] = [

    'LÁSZLÓ',
    'ISTVÁN',
    'JÓZSEF',
    'JÁNOS',
    'ZOLTÁN',
    'SÁNDOR',
    'FERENC',
    'GÁBOR',
    'ATTILA',
    'PÉTER',
    'TAMÁS',
    'ZSOLT',
    'TIBOR',
    'ANDRÁS',
    'IMRE',
    'LAJOS',
    'CSABA',
    'GYÖRGY',
    'GYULA',
    'MIHÁLY',
    'KÁROLY',
    'BALÁZS',
    'BÉLA',
    'RÓBERT',
    'MIKLÓS',
    'DÁVID',
    'DÁNIEL',
    'KRISZTIÁN',
    'ÁDÁM',
    'NORBERT',
    'PÁL',
    'BENCE',
    'ANTAL',
    'MÁTÉ',
    'SZABOLCS',
    'ROLAND',
    'GERGŐ',
    'RICHÁRD',
    'BÁLINT',
    'GERGELY',
    'MÁRK',
    'GÉZA',
    'ÁKOS',
    'VIKTOR',
    'ÁRPÁD',
    'LEVENTE',
    'MÁRTON',
    'JENŐ',
    'KÁLMÁN',
    'KRISTÓF',
    'ERNŐ',
    'PATRIK',
    'MARTIN',
    'BARNABÁS',
    'ENDRE',
    'DEZSŐ',
    'MÁTYÁS',
    'MILÁN',
    'DOMINIK',
    'MARCELL',
    'NÁNDOR',
    'SZILÁRD',
    'VILMOS',
    'ÁRON',
    'OTTÓ',
    'ERIK',
    'DÉNES',
    'ALEX',
    'ZSOMBOR',
    'BOTOND',
    'BERTALAN',
    'OLIVÉR',
    'KORNÉL',
    'RUDOLF',
    'BENEDEK',
    'ALBERT',
    'BENJÁMIN',
    'ADRIÁN',
    'GYŐZŐ',
    'ZSIGMOND',
    'ERVIN',
    'VINCE',
    'GUSZTÁV',
    'KEVIN',
    'ANDOR',
    'SZILVESZTER',
    'ELEMÉR',
    'IVÁN',
    'ZALÁN',
    'BARNA',
    'TIVADAR',
    'EMIL',
    'ARNOLD',
    'HENRIK',
    'CSONGOR',
    'KRISZTOFER',
    'LÓRÁNT',
    'ELEK',
    'ÁBEL',
    'RENÁTÓ',

    'MÁRIA',
    'ERZSÉBET',
    'KATALIN',
    'ILONA',
    'ÉVA',
    'ANNA',
    'ZSUZSANNA',
    'MARGIT',
    'JULIANNA',
    'JUDIT',
    'ÁGNES',
    'ANDREA',
    'ILDIKÓ',
    'ERIKA',
    'IRÉN',
    'KRISZTINA',
    'MAGDOLNA',
    'ESZTER',
    'MÓNIKA',
    'EDIT',
    'GABRIELLA',
    'SZILVIA',
    'ROZÁLIA',
    'MÁRTA',
    'ANITA',
    'ANIKÓ',
    'PIROSKA',
    'VIKTÓRIA',
    'TÍMEA',
    'KLÁRA',
    'IBOLYA',
    'GIZELLA',
    'TÜNDE',
    'TERÉZIA',
    'VERONIKA',
    'DÓRA',
    'ZSÓFIA',
    'ALEXANDRA',
    'CSILLA',
    'MELINDA',
    'NIKOLETT',
    'ADRIENN',
    'MARIANNA',
    'BEÁTA',
    'JOLÁN',
    'RENÁTA',
    'RÉKA',
    'ETELKA',
    'RITA',
    'BERNADETT',
    'BRIGITTA',
    'BARBARA',
    'GYÖNGYI',
    'EDINA',
    'ENIKŐ',
    'NÓRA',
    'HAJNALKA',
    'VIVIEN',
    'TERÉZ',
    'BORBÁLA',
    'ORSOLYA',
    'VALÉRIA',
    'PETRA',
    'ANNAMÁRIA',
    'ARANKA',
    'NOÉMI',
    'RÓZA',
    'BOGLÁRKA',
    'NIKOLETTA',
    'KITTI',
    'FANNI',
    'EMESE',
    'ANETT',
    'KLAUDIA',
    'LAURA',
    'LILLA',
    'RÓZSA',
    'IRMA',
    'KINGA',
    'BEATRIX',
    'ZITA',
    'ZSANETT',
    'GYÖRGYI',
    'EMMA',
    'SÁRA',
    'JÚLIA',
    'HENRIETTA',
    'DORINA',
    'DIÁNA',
    'SAROLTA',
    'MARIANN',
    'OLGA',
    'BIANKA',
    'BETTINA',
    'DOROTTYA',
    'LILI',
    'SZABINA',
    'IDA',
    'EVELIN',
    'VIRÁG'
  ].sort();

  private SearchTextValue = '';

  public listSearch = [];

  constructor(private dialogRef: MatDialogRef<AutocompComponent>) {

  }


  public get searchText() {
    return this.SearchTextValue;
  }

  public set searchText(value: string) {
    this.listSearch = this.options.filter(item => item.toUpperCase().includes(value.toUpperCase()));
    this.SearchTextValue = value;
  }

  submit(event) {
    event.preventDefault();
    this.dialogRef.close({status: true, value: this.SearchTextValue});
  }
}
